spring:
  application:
    name: bbang
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

twilio:
  sid: ${TWILIO_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone: ${TWILIO_PHONE}

jwt:
  key: ${JWT_KEY}