spring:
  application:
    name: bbang
  datasource:
    url: jdbc:postgresql://${HOST}:5432/bbang
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${HOST}
      port: 6379

twilio:
  sid: ${TWILIO_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone: ${TWILIO_PHONE}

jwt:
  key: ${JWT_KEY}